const config = [
  {
    title: 'TOKEN1',
    caption: '有趣和友好的互联网货币。与其他数字货币区别开来，拥有一个由友好人士组成的令人惊叹，充满活力的社区',
    url: '/images/tokens/0x0D8Ce2A99Bb6e3B7Db580eD848240e4a0F9aE153.png',
    description: [
      {
        id: 1,
        websiteButton: 'websiteButton',
        seeButton: '查看合约',
        startBlock: '开始区块：',
        endBlock: '结束区块：',
        estimatedEndTime: '预计结束时间：',
        salesVolumes: '销售数量：',
        totalFinancing: '筹资总额：',
        unitPrice: '单价：',
        myLPBalance: '我的LP余额：',
        oldNumberOfParticipants: '已参与数量：',
        quantityToBeCollected: '待领取数量：',
        numberOfParticipants: '参与数量',
        participateIn: '参与',
        receive: '领取',
      },
    ],
  },
  {
    caption: '有趣和友好的互联网货币。与其他数字货币区别开来，拥有一个由友好人士组成的令人惊叹，充满活力的社区',
    title: 'TOKEN2',
    url: '/images/tokens/0x1FFD0b47127fdd4097E54521C9E2c7f0D66AafC5.png',
    description: [
      {
        id: 2,
        websiteButton: '官网',
        seeButton: '查看合约',
        startBlock: '开始区块',
        endBlock: '结束区块',
        estimatedEndTime: '预计结束时间',
        salesVolumes: '销售数量',
        totalFinancing: '筹资总额',
        unitPrice: '单价',
        myLPBalance: '我的LP余额',
        oldNumberOfParticipants: '已参与数量：',
        quantityToBeCollected: '待领取数量：',
        numberOfParticipants: '参与数量',
        participateIn: '参与',
        receive: '领取',
      },
    ],
  },
  {
    caption: '有趣和友好的互联网货币。与其他数字货币区别开来，拥有一个由友好人士组成的令人惊叹，充满活力的社区',
    url: '/images/tokens/0x007EA5C0Ea75a8DF45D288a4debdD5bb633F9e56.png',
    title: 'TOKEN3',
    description: [
      {
        id: 3,

        websiteButton: '官网',
        seeButton: '查看合约',
        startBlock: '开始区块',
        endBlock: '结束区块',
        estimatedEndTime: '预计结束时间',
        salesVolumes: '销售数量',
        totalFinancing: '筹资总额',
        unitPrice: '单价',
        myLPBalance: '我的LP余额',
        oldNumberOfParticipants: '已参与数量：',
        quantityToBeCollected: '待领取数量：',
        numberOfParticipants: '参与数量',
        participateIn: '参与',
        receive: '领取',
      },
    ],
  },
  {
    caption: '有趣和友好的互联网货币。与其他数字货币区别开来，拥有一个由友好人士组成的令人惊叹，充满活力的社区',
    url: '/images/tokens/0x7e396BfC8a2f84748701167c2d622F041A1D7a17.png',
    title: 'TOKEN4',
    description: [
      {
        id: 4,

        websiteButton: '官网',
        seeButton: '查看合约',
        startBlock: '开始区块',
        endBlock: '结束区块',
        estimatedEndTime: '预计结束时间',
        salesVolumes: '销售数量',
        totalFinancing: '筹资总额',
        unitPrice: '单价',
        myLPBalance: '我的LP余额',
        oldNumberOfParticipants: '已参与数量：',
        quantityToBeCollected: '待领取数量：',
        numberOfParticipants: '参与数量',
        participateIn: '参与',
        receive: '领取',
      },
    ],
  },
  {
    caption: '有趣和友好的互联网货币。与其他数字货币区别开来，拥有一个由友好人士组成的令人惊叹，充满活力的社区',
    url: '/images/tokens/0x0D8Ce2A99Bb6e3B7Db580eD848240e4a0F9aE153.png',
    title: 'TOKEN5',
    description: [
      {
        id: 5,

        websiteButton: '官网',
        seeButton: '查看合约',
        startBlock: '开始区块',
        endBlock: '结束区块',
        estimatedEndTime: '预计结束时间',
        salesVolumes: '销售数量',
        totalFinancing: '筹资总额',
        unitPrice: '单价',
        myLPBalance: '我的LP余额',
        oldNumberOfParticipants: '已参与数量：',
        quantityToBeCollected: '待领取数量：',
        numberOfParticipants: '参与数量',
        participateIn: '参与',
        receive: '领取',
      },
    ],
  },
]
export default config
